# Generated by Django 5.0.3 on 2024-04-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_sizevariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
