# Generated by Django 5.0.3 on 2024-04-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_alter_tshirt_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirt',
            name='slug',
        ),
    ]
