# Generated by Django 5.0.3 on 2024-04-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_remove_tshirt_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
